/*
 * Generated by MTK Easy PinMux Tool Version 2.2.0 for 7687. Copyright MediaTek Inc. (C) 2015.
 * 2017-06-26 15:16:46:0398
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
